# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
name: spyglass
channels:
  - conda-forge
  - franklab
  - edeno
dependencies:
  - python>=3.9,<3.10
  - jupyterlab>=3.*,<4 # leave at v3 to support jupyterlab-git
  - jupyter_contrib_nbextensions==0.5.1
  - jupyterlab-git
  - nbgitpuller=1.1.*
  - pydotplus
  - dask
  - pip
  - position_tools
  - numpy<1.24
  - track_linearization>=2.3
  - ripple_detection
  - non_local_detector
  - matplotlib
  - seaborn
  - bottleneck
  - ipympl
  - tqdm
  - pyfftw<=0.12.0  # used by ghostipy. install from conda-forge so that it works on Mac ARM processors
  - pip:
      - pubnub<6.4.0
      - spikeinterface>=0.98.2,<0.99
      - pynwb>=2.2.0,<3
      - hdmf>=3.4.6
      - datajoint>=0.13.6
      - ghostipy
      - pymysql
      - sortingview>=0.11
      - figurl-jupyter
      - git+https://github.com/LorenFrankLab/ndx-franklab-novela.git
      - pyyaml
      - click
      - "black[jupyter]"
      - spyglass-neuro
