# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
name: spyglass
channels:
  - conda-forge
  - franklab
  - edeno
dependencies:
  - python>=3.9,<3.10
  - jupyterlab>=3.*,<4 # leave at v3 to support jupyterlab-git
  - jupyter_contrib_nbextensions==0.5.1
  - jupyterlab-git
  - nbgitpuller=1.1.*