#!/bin/bash

git clone https://github.com/LorenFrankLab/spyglass.git
cd spyglass
cat << EOF > dj_local_conf.json
{
  "database.host": "localhost",
  "database.password": "tutorial",
  "database.user": "root",
  "database.port": 3306,
  "database.reconnect": true,
  "connection.init_function": null,
  "connection.charset": "",
  "loglevel": "INFO",
  "safemode": true,
  "fetch_format": "array",
  "display.limit": 12,
  "display.width": 14,
  "display.show_tuple_count": true,
  "database.use_tls": null,
  "enable_python_native_blobs": true,
  "filepath_checksum_size_limit": null,
  "stores": {
    "raw": {
      "protocol": "file",
      "location": "/home/jovyan/shared-readwrite/nwb/raw",
      "stage": "/home/jovyan/shared-readwrite/nwb/raw"
    },
    "analysis": {
      "protocol": "file",
      "location": "/home/jovyan/shared-readwrite/nwb/analysis",
      "stage": "/home/jovyan/shared-readwrite/nwb/analysis"
    }
  },
  "custom": {
    "spyglass_dirs": {
      "base": "/home/jovyan/shared-readwrite/nwb"
    },
    "kachery_dirs": {
      "cloud": "/home/jovyan/shared-readwrite/.kachery_cloud"
    },
    "kachery_zone": "franklab.collaborators"
  }
}
EOF
cd notebooks