#!/bin/bash

MYSQL_AVAILABLE=$(command -v mysql &> /dev/null)
SQL_FILE="/home/jovyan/shared-public/prepopulate.sql"

if $MYSQL_AVAILABLE && [ -f "$SQL_FILE" ]; then
    echo "Populating:  YES."
    mysql -h localhost -u root --password=tutorial < "$SQL_FILE"
    MYSQL_EXIT_STATUS=$?
    if [ $MYSQL_EXIT_STATUS -ne 0 ]; then
        echo "Populating: ERROR. $MYSQL_EXIT_STATUS"
    fi
elif ! $SQL_FILE_EXISTS; then
    echo "Populating:  NO. Executable not found"
else
    echo "Populating:  NO. SQL file not found"
fi

exec "$@" 
